#Auto variables for Packer

vcenter_server="vcenter01.home"
#vsphere_username=""
#vsphere_password=""
datastore="datastore2"
host="esxhost01.home"
datacenter="Datacenter"
folder="Templates"
cluster="Cluster"
network="Non-OCP"
boot_wait="5s"
boot_iso="[datastore2] ISOs/Ubuntu/ubuntu-22.04.1-live-server-amd64.iso"
guest_os_type="ubuntu64Guest"
memsize="4096"
numvcpus="2"
disk_size="61440"
ssh_password="P@ssw0rd"
ssh_username="ubuntu"
#vm_name="ubuntu2204"
template_vm_name="pkr_tmpl_ubuntu2204"
install_config=""